### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by SchulerSimon** [YuntechNet/AtomicP2P#28]
Hello,

My name is Simon, I am a colleague of Lindrit. He is working on his PhD for now, so I took over his work.

I was experimenting with your Library quite a bit and I have a few questions:

Please find my source code attached, just rename main.txt to main.py and execute.
[main.txt](https://github.com/YuntechNet/AtomicP2P/files/3477146/main.txt)

Question1:

Why is "print(p1.connectlist)" in line 108 empty?

Question2:

how to properly join a network as a peer?

Lets say I have 6 peers and I want to connect them all up, how would I do that so that every peer gets all the messages that all the other peers send?

Question3:

How can I find out if 2 peers are connected? because p1.connectlist dosent seem to work.

Thank You so much for Your time.

Kind regards Simon

**Comment by jackey8616** [comment]
Hi Simon,

A1:
Line108's empty content is normal.
Because Peers need handshake.
There is a Ack packet will be send back after Join Packet been accepted.

I simply move two lines to the place before broadcast been call, and you can get content.
```python

p1.connect(p2)
time.sleep(2)
# p2.connect(p1)
# time.sleep(2)

time.sleep(2)

print(p1.connectlist)
print(p2.connectlist)

p1.send_broadcast("hi1")
p2.send_broadcast("hi2")
```

A2:
Currently these is two ways to join a peer into an exists net.
Command way, and Programming way.
Actually both these two way is the same, since command way is just a wrap of another one.

I've see that you are using onCommand to send a join command which is find.
If you are really want to use programming way, please check [this out](https://github.com/YuntechNet/AtomicP2P/blob/9ae5dc464be58c6c1ea23c660236cb46a8acaaab/atomic_p2p/peer/command.py#L56-L61).

A3:
Since connectlist is not malfunction, I think you can iterate it.

BTW,
A join method has been consider to be add in version 0.0.5,
and please follow any changes in near feature.

Fill free to reopen this issue if you still get any trouble.
